### ISSUE TITLE
block comment don't give rise to foldable blocks

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#101]
```nim

#[
should show a foldable icon so this comment is foldable
]#


# note the foldable icon (triangle) here
proc fun()=
  proc fun2()=
    discard
  discard

fun()

```

![image](https://user-images.githubusercontent.com/2194784/42988519-b8b98c3e-8bb1-11e8-93bc-67ed2d96e460.png)

* PENDING [Code Folding should be based on syntax, not on indentation level · Issue #101 · SublimeTextIssues/Core](https://github.com/SublimeTextIssues/Core/issues/101)

**Comment by Varriount** [comment]
Do you know of a way to enable this? Even the Python syntax doesn't allow folding triple-quoted strings.

**Comment by timotheecour** [comment]
https://www.sublimetext.com/docs/3/api_reference.html
```
fold([regions]) | bool | Folds the given regions, returning False if they were already folded
-- | -- | --
fold(region) | bool | Folds the given region, returning False if it was already folded
unfold(region) | [Region] | Unfolds all text in the region, returning the unfolded regions
unfold([regions]) | [Region] | Unfolds all text in the regions, returning the unfolded regions
```

example: syntax based folding:
https://github.com/jamalsenouci/sublimetext-syntaxfold/blob/master/SyntaxFold.py

**Comment by Varriount** [comment]
See this:
```
Note: This plugin does not create folding markers (the functionality for creating these markers is not exposed within the Sublime Text API). The folding functionality provided by this plugin relies on using keyboard shortcuts assigned by the User or by invoking fold commands through the command panel.
```

**Comment by Varriount** [comment]
@timotheecour ^

The above quote means that even if this functionality was implemented, it would only be accessible via hotkeys. To me, this significantly reduces the usefulness. Furthermore, there already appears to be a plugin which implements a generic approach to this problem.
