### ISSUE TITLE
name clashes with https://github.com/h3rald/nimline

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#102]
kind of a nit but thought I'd mention it:

/cc @h3rald @Varriount this could become a problem once these are published via nimble.
it's also an inconvenience when user does:
```
git clone https://github.com/h3rald/nimline
git clone https://github.com/Varriount/NimLime
```
(eg on case insensitive systems like OSX, windows, this will fail, so user has to use a workaround)

IMO nimline makes sense more as line editing (cf https://github.com/h3rald/nimline) than as a sublime plugin;  maybe NimSublime instead? IIRC it's possible to rename git repos relatively seamlessly, see https://stackoverflow.com/questions/2041993/how-to-rename-a-git-repository

**Comment by Varriount** [comment]
There's still a one character difference "M" vs "N".

**Comment by timotheecour** [comment]
> There's still a one character difference "M" vs "N".

lol, totally missed that, sorry for the noise!
