### ISSUE TITLE
syntax highlight messed up after a point

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#104]
reduced from /Users/timothee/git_clone/nim/Nim/lib/pure/hashes.nim

```nim
proc hashData() =
  when false:
    asm """`baz`;"""

proc hash(): Hash =
  when false:
    asm """
    """
  else:
    result = 0

proc foo() = discard
```

![image](https://user-images.githubusercontent.com/2194784/44072096-bc5fe272-9f41-11e8-8ecb-a4ca4d643880.png)

**Comment by onionhammer** [comment]
Strange, it works fine in your code snippet here (which is powered by NimLime)

**Comment by Varriount** [comment]
Works for the current development build (and probably master too).

**Comment by timotheecour** [comment]
* could we re-open ? still messed up for me

* I'm on OSX how about you (for whomever it works)

* could you share a screenshot?

**Comment by Varriount** [comment]
![image](https://user-images.githubusercontent.com/524596/48035771-6cd0b900-e133-11e8-874b-2c795ddc892b.png)

**Comment by timotheecour** [comment]
sigh... I have no idea why it wouldn't work for me... are you on OSX as well? 
I'm on dev build 3180 and pretty sure I had same issue with latest stable build

**Comment by timotheecour** [comment]
duplicate of https://github.com/Varriount/NimLime/issues/104 ; i found the root cause, will discuss in 104
