### ISSUE TITLE
how to reload NimLime without re-opening sublimetext?

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#115]
I even tried AutomaticPackageReloader but didn't work see https://github.com/randy3k/AutomaticPackageReloader/issues/15

also tried various stuff here https://forum.sublimetext.com/t/how-can-i-reload-a-plugin-in-sublime-console/34325

**Comment by Varriount** [comment]
Fixed in https://github.com/Varriount/NimLime/commit/54337b88cb8e57c5886746808ce7522da0d9d960 .

**Comment by timotheecour** [comment]
for reference:

```
import sublime_plugin
sublime_plugin.reload_plugin('NimLime.core.commands.nimcheck')
```

**Comment by Varriount** [comment]
Even though the modules themselves don't appear in the above log, they do appear to be reloaded:
[](https://thumbs.gfycat.com/MealySnoopyFlatcoatretriever-size_restricted.gif)

**Comment by randy3k** [comment]
It’s because NimLime.core.commands has a custom loader https://github.com/Varriount/NimLime/blob/master/nimlime_core/commands/__init__.py

**Comment by Varriount** [comment]
See https://github.com/randy3k/AutomaticPackageReloader/issues/19
