### ISSUE TITLE
NimLime should use relative import instead of changing the python search path, it breaks AutomaticPackageReloader

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#116]
/cc @Varriount 
see https://github.com/randy3k/AutomaticPackageReloader/issues/15#issuecomment-435594173

this would fix https://github.com/Varriount/NimLime/issues/115

**Comment by Varriount** [comment]
I'll look into fixing this - I'm removing ST2 support for NimLime anyway, which is what that code is there for (I think).

**Comment by Varriount** [comment]
Fixed in https://github.com/Varriount/NimLime/commit/54337b88cb8e57c5886746808ce7522da0d9d960
