### ISSUE TITLE
nimsuggest sources should not be copied inside NimLime; use a dependency instead

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#117]
is there any reason nimsuggest sources are copied inside NimLime?
this doesn't seem like a good idea, eg in case bugs get fixed upstream, NimLime won't benefit from it.

possible alternatives:
 *just use (user provided maybe) path to Nim sources (if no change needed)
* PR to get changes accepted upstream, if possible
* use a fork of Nim if needed, which can then be regularly updated against upstream

**Comment by Varriount** [comment]
Nimsuggest has, quite frankly, been more trouble than it's worth to support. The TCP mode disconnects after a single command (which is *really* inefficient) and the standard input mode is a pain to support across platforms. 

Furthermore, Nimsuggest requires that "dirty" (modified) files be written to disk. If one wants to get suggestions on every keystroke, one either has to suffer major performance penalties (lets save a dirty file to disk every keystroke!) or write a complex caching/state management algorithm.

Until the situation becomes more tenable (or I find the time to reimplement it), I'm removing Nimsuggest support. This can be seen at https://github.com/Varriount/NimLime/commit/54337b88cb8e57c5886746808ce7522da0d9d960 .
