### ISSUE TITLE
`nim check` errors don't show up on branch `restructure-for-st3`

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#118]
/cc @Varriount 
on branch `master` `nim check` errors do show up
on branch `restructure-for-st3` `nim check` errors don't show up anymore...

**Comment by Varriount** [comment]
Can you please post the contents of your user settings? I'm not encountering this issue.
Also, what OS are you using?

**Comment by timotheecour** [comment]
upon further inspection this is a regression  : I had fixed this bug 3 days ago in https://github.com/Varriount/NimLime/pull/114 but the issue came back with branch `estructure-for-st3`

the relevant setting is `--listFullPaths` in ~/.config/nim/nim.cfg which causes absolute paths (which I handled correctly in https://github.com/Varriount/NimLime/pull/114)

I'm on OSX

> Can you please post the contents of your user settings? I'm not encountering this issue.

shouldn't be relevant but here goes:
```
{
    "check.on_save.enabled": true, 
    "nim.executable": "/Users/timothee/.nimble/bin/nim",
    "debug_mode": true,
    "nimsuggest.executable": "/Users/timothee/.nimble/bin/nimsuggest",
    "error_handler.logfile_path": "/tmp/nimline.logs",
}


```
