### ISSUE TITLE
github syntax highlight for Nim extensions (nims, nim.cfg, nimble)

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#125]
@Varriount I'm trying to figure out how to syntax highlight nim code (inlcuding nimble and nim.cfg) files on github, see https://github.com/github/linguist/pull/4295 which just got merged and changes Nim section to:

https://github.com/github/linguist/blob/ee29c920f6ecb56750ccb4607b8852dab19082b4/lib/linguist/languages.yml#L3099-L3112

the docs in https://github.com/github/linguist says:
> Linguist detects the language of a file but the actual syntax-highlighting is powered by a set of language grammars which are included in this project as a set of submodules as listed https://github.com/github/linguist/blob/master/vendor/README.md

this points to:
Nim: https://github.com/Varriount/NimLime

hence this is why I'm asking you here.

https://github.com/Varriount/NimLime/tree/master/Syntaxes shows
Nim.tmLanguage
Nim_Cfg.tmLanguage
etc

is my PR https://github.com/github/linguist/pull/4295 wrong (for eg, classify nim.cfg as Nim instead of Nim_Cfg) ? 
for eg, for D, there's a single `D.tmLanguage` in https://github.com/textmate/d.tmbundle/blob/master/Syntaxes/
even though 2 extensions are shown here:
```
D:
  type: programming
  color: "#ba595e"
  extensions:
  - ".d"
  - ".di"
  ace_mode: d
  codemirror_mode: d
  codemirror_mime_type: text/x-d
  language_id: 80
```

https://github.com/github/linguist/blob/ee29c920f6ecb56750ccb4607b8852dab19082b4/lib/linguist/languages.yml#L967-L976

but I don't think it would make sense to have nims, nimble, nim.cfg files reported as Nim_Cfg, Nims, Nimble in github language stats, they should just be Nim (as I was trying to do in this PR)

/cc @pchaigno if you have any tips, thanks!

**Comment by pchaigno** [comment]
If your issue is that Nim syntax highlighting doesn't work, it's normal. Your changes will take effect with the next Linguist release. There's usually one every month.

**Comment by pchaigno** [comment]
> thanks for replying; could that be documented in https://github.com/github/linguist/blob/master/README.md ?

It will be documented in the new FAQ (cf. github/linguist#4271).
