### ISSUE TITLE
ESC should remove nimfix error annotations in source file

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#131]
/cc @Varriount let me know if you need more details/description

**Comment by Varriount** [comment]
My biggest concern is that this would conflict with other plugins. Plus, users can create their own key combos.
Given that there's already a command in the command palette, would this really add anything substantial?

**Comment by timotheecour** [comment]
how do I remove the red error annotations here?

![image](https://user-images.githubusercontent.com/2194784/48752123-9feb7000-ec3c-11e8-82b9-5ab4da3d6945.png)

**Comment by Varriount** [comment]
@timotheecour The used can create a custom hotkey using the same command that is run from the command palette .

**Comment by timotheecour** [comment]
> the same command that is run from the command palette

- [ ] sorry for being thick... which command is that?

- [ ] related question, where are these defined in code?
`insert_snippet` etc

grepping for it I only see:
```
Default (Linux).sublime-keymap:2:35:    {"keys": ["f12"], "command": "gotodef", "context":
Default (OSX).sublime-keymap:2:35:    {"keys": ["f12"], "command": "gotodef", "context":
Default (Windows).sublime-keymap:2:35:    {"keys": ["f12"], "command": "gotodef", "context":
```
but I'm not seeing it defined in py file in NimLime repo,  as follows:
```py
class gotodef(sublime_plugin.WindowCommand):
```
