### ISSUE TITLE
Pragma Completion

### ISSUE THREAD

**Issue by Varriount** [Varriount/NimLime#17]
There should be a way to mimick/hack brace completion such that pragma notation ( '{..}' ) is also done.

**Comment by onionhammer** [comment]
You mean to automatically insert the ending '.}' as opposed to just '}'?

**Comment by Varriount** [comment]
Yes. In my mind, you would type '{.' and the other '.}' would appear. 
Even better would be if only '{' would have to be typed in. I imagine it would require techniques similar to what's done with the doc-comment continuation mechanism.

**Comment by onionhammer** [comment]
+1 sounds good to me :)

**Comment by Varriount** [comment]
Ok, the big thing this is going to require is some modification to the language definition. We'll need some sort of 'incomplete pragma' scope that the function can check.

**Comment by Varriount** [comment]
Implemented in commit deec1f36b15e8b1bf1d98e58fdab4efdeab859ce
