### ISSUE TITLE
Syntax highlighting of 'import' statement does not work properly

### ISSUE THREAD

**Issue by gmpreussner** [Varriount/NimLime#20]
The following will highlight the first `/` in white (correct) and all subsequent `/` in red (incorrect - division operator?):

```nimrod
import foo/a, foo/b, foo/c
```

The following will highlight `import` in white (incorrect) and all `/` in red (incorrect):

```nimrod
import
  foo/a,
  foo/b,
  foo/c
```

**Comment by Varriount** [comment]
Fixed.
