### ISSUE TITLE
Identifiers are not highlighted correctly when containing Unicode glyphs

### ISSUE THREAD

**Issue by ozra** [Varriount/NimLime#26]
Well, the title sums it up.

```nim
proc hash‒ignore‒style*(x: string): THash =    # proc ident is wacked when Unicodes used
  var h: THash = 0
  var i = 0
  let x‒len = x.len     # len is highlighted when there's a Unicode before in the ident
  while i < x‒len:
    var c = x[i]
    if is‒middot‒rune(cstring(x), i):    # proc ident is wacked when Unicodes used
      inc(i, 2)
  # ...
```
(The dash in the example is ofc. the Unicode...)

**Comment by Varriount** [comment]
Huh, odd.

Looking at the syntax definition files, I don't see any obvious occurrences of selecting for only alphanumeric characters. '\w' is used fairly consistently.  
Tell me, what category is the Unicode character your using in? Does it fit it any of the categories that '\w' matches for, as described on [this page](http://www.geocities.jp/kosako3/oniguruma/doc/RE.txt)? If not, then the syntax definition file is probably going to need some modifying to include the additional Unicode categories.

**Comment by ozra** [comment]
Well, basically Nim syntax allows _any_ utf-8 legal Unicode rune in identifiers. That one in the example is called "FIGURE DASH" (0x2012). `\w`, ofc. only matches "word-like" glyphs. I guess something like `[\w\x{80}-\x{some-fucking-high-num}]` should do it? with "some...", being some upper bound in Unicode world?

**Comment by ozra** [comment]
I tried hacking your package in sublime, and that seems to work. I'll mess a bit more..
