### ISSUE TITLE
Make the syntax matching more detailed

### ISSUE THREAD

**Issue by ozra** [Varriount/NimLime#31]
The distinction between elements is still a bit crude.

**Comment by ozra** [comment]
I've been tinkering on fixing bugs and making it a bit more detailed. So far, quite som minor bugs fixed and (don't mind the color scheme, but the separations):

![screenshot from 2015-06-09 00 49 58 coloring](https://cloud.githubusercontent.com/assets/563674/8047154/0f63bafa-0e42-11e5-9319-37942e676825.png)

**Comment by Varriount** [comment]
Looks nice!

**Comment by ozra** [comment]
I was thinking of taking the time some evening soon to add a kw-keywordname class for each keyword, so they can be coloured individually if wanted. Don't really know if anyone would be in need of that though? Might slow down highlighter?

**Comment by Varriount** [comment]
I doubt that adding additional characters to the group names will cause any noticeable slowdown.
