### ISSUE TITLE
Feature request: 80-char notification

### ISSUE THREAD

**Issue by apense** [Varriount/NimLime#34]
In https://github.com/Araq/Nim/wiki/Style-Guide-for-Nim-Code#spacing-and-whitespace-conventions it's mentioned that *Lines should be no longer than 80 characters*. 
Would it be possible to have a non-obtrustive notice when the code exceeds this? Maybe a dashed vertical grey line or something similar once the code reaches that length? I feel there's editors that do this, but I can't come up with any examples at the moment.
Kind of like notification of a new page on a word processor. The compiler doesn't complain when you push past 80, so it shouldn't be too angry.

Thanks for the consideration!

**Comment by mathsaey** [comment]
This convention is not exclusive to nim, as it is used by a lot of other languages. As such, I think this feature should be provided at the sublime text level. In fact, sublime already provides this. Just add the following to your `Packages/User/preferences.sublime-settings` file.

	"rulers":
	[
		80
	],

If you don't want to get this separator for other languages, you can just add the same setting to your language specific settings, which can be found at `Packages/User/nimrod.sublime-settings`

**Comment by Varriount** [comment]
Perhaps if/when Nim/NimLime gets a proper linter. Even so, such a desire is low priority; the rulers setting along with `find` and the regex `.{81,}` should suffice.

**Comment by apense** [comment]
I should really have known about the Sublime feature before. Thanks for that. I agree it's more of a linter issue. I'm gonna close this now.
