### ISSUE TITLE
Highlighting vs GitHub

### ISSUE THREAD

**Issue by ozra** [Varriount/NimLime#38]
The changes I've made to add more nested scopes and details to matching has caused some problems. GitHub, specifically, adds weird colors to classes that Sublime don't touch in standard color schemes.

I think the best route might be to isolate github coloring to its own repo.

Alternatively separate a "simple" and "advanced detail" syntax.

Prio 1 now, I will roll back to just having bug fixes and no additions until I (or anyone else) can take time to figure out a more cross-viewer scope/class compatible naming scheme.

**Comment by Varriount** [comment]
I think I've said this before, bit of not, I'll state it here: The syntax definition files for NimLime are not tied in any way with Github's highlighter.

**Comment by ozra** [comment]
Aha, ok, I thought they were the basis. They are separate? Because it seems just a day or so ago github started highlighting nim differently (?)

In any event the PR cleans up a bit more for NimLime. I found one highlight bug in one file yesterday, so I'm gonna squash that one too, but maybe after the weekend. So I think the PR is better pulled then not atm.
