### ISSUE TITLE
NimSuggest not working under Ubuntu

### ISSUE THREAD

**Issue by andreaferretti** [Varriount/NimLime#48]
Using Sublime 3 under Ubuntu 15.04, with NimLime installed through Package Control.

Apparently, autocompletion does not work at all. I have tried:

* adding the explicit path to the `nim` executable under the user settings
* enabling `enable_nim_completions` and `provide_immediate_nim_completions`
* adding the `nim_update_completions` block under the user keymap

Under the console I sometimes see the error `FileNotFoundError: [Errno 2] No such file or directory: '/home/papillon/.config/sublime-text-3/Packages/NimLime/Default (Linux).sublime-keymap'`.

Is there a way to debug the issue?

**Comment by Varriount** [comment]
Unfortunately, the only way to really debug ST plugins is to add print statements. I guess you could try looking at the completion code, and seeing where the error originates.
