### ISSUE TITLE
After saving a *.nim file it opens a blank tab with "nimlime" title

### ISSUE THREAD

**Issue by HaCk3Dq** [Varriount/NimLime#50]
thats it :)

**Comment by the-shank** [comment]
+1 I am also facing this issue

**Comment by Varriount** [comment]
Is this with the most recent stable (downloaded via Package Control) or the current master branch?

**Comment by HaCk3Dq** [comment]
@Varriount, most recent stable

**Comment by the-shank** [comment]
@Varriount my system details are:
> OSX Yosemite
> Nim 0.11
> Nimlime - Latest via Package Control

**Comment by Varriount** [comment]
@the-shank @HaCk3Dq What happens when setting the setting value on [this line](https://github.com/Varriount/NimLime/blob/master/NimLime.sublime-settings#L166) to 'false'?

**Comment by the-shank** [comment]
@Varriount yes that does it ! Sorry for wasting your time :(

**Comment by Varriount** [comment]
It shouldn't do that though, and it shouldn't be set to true by default, so I'm going to leave the issue open.

**Comment by HaCk3Dq** [comment]
@Varriount, yeah, thnx for the fix :D
pls update the default settings)

**Comment by HaCk3Dq** [comment]
Hm, ive updated all packages in sublime: the issue is still here ;(

**Comment by Varriount** [comment]
@HaCk3Dq If you update all packages, and you've made changes to the default NimLime.sublime-settings file, the changed settings will be overriden. Use the user settings files.

**Comment by HaCk3Dq** [comment]
@Varriount 

`Nimble.sublime-settings`:

`"check.on_save.output.show": false`

So it shouldn`t show this tab, ive added this line to my user settings file too. Same shit

**Comment by mhstp** [comment]
I'm having this problem as well. Pretty sure I'm using the current code from the repository. I don't want it checking every time I save and I certainly don't want empty 'nimlime' files. But I can't stop either. This is my User settings (garbage exe names to try to stop checking):

{
  "nim.executable": "gjr mvg",
  "nimble.executable": "rtgtgvt",
  "nimsuggest.executable": "tgrtgvtrg",
  "error_handler.enabled": false,
  "check.on_save.enabled": false,
  "check.current_file.enabled": false,
}

**Comment by Varriount** [comment]
When did you last update the plugin?

**Comment by mhstp** [comment]
Thanks for prompt reply. It was this week. 

I've now uninstalled Sublime and installed the portable version (on Windows 7). Reduced User settings to 

{
	"check.on_save.enabled": false,
}

Fingers crossed! :)

**Comment by Varriount** [comment]
I forgot to ask - which version of Sublime Text are you using, and when did this behavior first start?

**Comment by mhstp** [comment]
It was ST3, not sure what build as it's gone now. I've only been using Nim for a week or two and fault started with normal install of NimLime (not from repository) as soon as nim appeared on PATH. (My PATH was too long at first so nim wasn't there at first.) I also had a bunch of other packages installed. 

Current fresh install of ST3 portable and NimLime seem to be working fine! I'll let you know if it does anything weird again. Sorry I couldn't supply more detailed info. Thanks for your help.

  Martin

**Comment by mhstp** [comment]
It has done it again. It was all right on Sunday and Monday but after starting ST3 just now it is checking on save again and opening an empty nimlime file on each save. My user preferences haven't changed. I didn't even close down Windows over night. ST3 had NOT been running over night.

I have found a workaround though -- delete the NimLime directory in Data/Cache.

Portable ST3 build is 3103 and NimLime was from GitHub on Sunday (via Package Control). Other packages installed are Package Control and Side Bar Enhancement. 

Martin

**Comment by Varriount** [comment]
Sigh... I haven't found anything yet (but then again, I can't reproduce it on my system).
There's a fix I need to push anyway, so I'll release a minor update today with some debugging calls added around the output functions. You'll need to add the `"debug_mode": true` key to your settings to enable debug output to the dev console.

**Comment by mhstp** [comment]
OK, I'll look out for that.

**Comment by Varriount** [comment]
Ok, release pushed. It sometimes takes up to 30 minutes for Package Control to actually 'see' the new release. Remember to set the 'debug_mode' setting to True.

**Comment by mhstp** [comment]
OK, today's NimLime installed and debug mode enabled. Behaving properly so far.

**Comment by mhstp** [comment]
Is the dev console the one shown using ctrl-`? Should I be seeing anything in there when I save a Nim file?

**Comment by Varriount** [comment]
Yes, the dev console is the one brought up by ctrl+`.
The debug function calls I've added should output data whenever a command writes it's output to a view.

**Comment by mhstp** [comment]
Hmm. I've removed the NimLime directory in Data/Cache again and Re-enabled check on save. My settings are:

{
	"check.on_save.enabled": true,
	"debug_mode": true
}

I saved a Nim file that contains an error and NimLime has highlighted the error without opening a nimlime file and reported in the status bar that Nim check has finished. All good but I'm not seeing any extra messages in the console.

**Comment by Varriount** [comment]
Well, that's expected. Debug information will only be printed when those extra output tabs are being created.

**Comment by mhstp** [comment]
Ah, right. I'll see what happens over next few days.

All the best,
Martin
