### ISSUE TITLE
NimSuggest not working under Windows

### ISSUE THREAD

**Issue by cryzed** [Varriount/NimLime#54]
I couldn't get NimSuggest working using Sublime Text 3, Build 3095 and Windows 7. No combination of settings even attempted to spawn the console window. The bug seems related to [NimSuggest not working under Ubuntu](https://github.com/Varriount/NimLime/issues/48) -- the complete feature seems to be broken or only working under special circumstances.

**Comment by Varriount** [comment]
There's currently progress being made on revamping nimsuggest support (check the restructured-hierarchy branch in about 8 hours).

That being said, with the way nimsuggest requires  reading a disk file, we still won't have instant suggestion support (too much latency) . :(

**Comment by cryzed** [comment]
That's good to hear! Regarding the latter: The latency comes from having to save the modified buffer to a temporary directory? A temporary workaround for now would be to use a RAMDisk which should mostly eliminate that delay or at least reduce it greatly.

**Comment by Varriount** [comment]
Now that I think about it, there are some possibilities that might reduce latency:
- Use O_TEMPORARY/FILE_ATTRIBUTE_TEMPORARY when opening the dirty file. This should reduce actual disk IO, as well as clean up files when Sublime Text exits.
- Use a heuristic to determine which parts of the file have been modified. Sublime Text doesn't expose a direct way to get the changes made to a file, so something based on view.sel() will have to be used (and even that won't be 100% accurate, just look at the checks doccontinue.py has to do).

**Comment by cryzed** [comment]
I'm not sure if I follow entirely. Are you planning on only writing the modified parts back to the temporary file that is read by NimSuggest? Would that actually reduce the latency? I think 99% of the latency would originate in the CPU scheduling -- i.e. suspending the process for an I/O operation and then waiting for the process to be scheduled again. Then again, I'm not familiar with the file attributes you mentioned, so maybe there are some changes in the scheduling / filesystem behavior I'm not aware of.

Regarding getting the difference between two buffer states: what about keeping the current file buffer in memory until autocompletion is triggered again and then using [difflib](https://docs.python.org/3/library/difflib.html) to compare the last known state of the buffer with the current one. This way it should be relatively easy to find the modified lines.

**Comment by Varriount** [comment]
@cryzed I'm thinking about the use case where autocomplete is activated by (nearly) every keystroke. To tell the truth, I don't know what the bottleneck is (or will be) yet.  
I'm planning to get manual autocomplete, lookup, etc. to work first, which will at least let others test the main logic. From there, I should be able to profile sections of the code (yay for profile_tools.py) to test what parts of the logic take the most time.
I guess I just assumed that writing the entire file out to disk (in Sublime Text), then reading it back in (in Nimsuggest) would take the most time, since those are blocking operations.

**Comment by cryzed** [comment]
I agree, those will probably take the most time. And yes, running the file through difflib on each keystroke would probably be too CPU intensive then, so being able to guarantee that changes have only been made within a certain scope would probably make this operation more efficient. You are right, it's hard to figure out where the bottleneck will actually be. Thank you very much for working on this and putting in the effort.
