### ISSUE TITLE
Default settings aren't loaded, strange settings path etc.

### ISSUE THREAD

**Issue by cryzed** [Varriount/NimLime#55]
Hey, I added some print statements to AutoComplete.py from the restructure-hierarchy branch and noticed some strange things:

For one, you are attempting to load the settings from a file called "nim.sublime-settings" which is only created when you store your plugin-related settings in the syntax-specific configuration files for *.nim files (and nowhere that I could find is explicitly mentioned that you have to do it this way).

Usually plugins attempt to load their default settings from the plugin settings: "Preferences->Package Settings->NimLime->Settings -- Default/Settings -- User", which doesn't seem to happen currently at all (you can change this by just loading "NimLime.sublime-settings" which should take care of interpolating all the settings from different locations for you, afaik).

You also check for a setting called "nim_compiler_executable" which should be called "nim.executable" (in the code and in the docs) from what I can tell, and if it doesn't exist you silently return.

After setting the correct "nim_compiler_executable" I added some more print statements. The command that is executed in the end seems to look like this:

    C:\Nim-devel\bin\nim.exe --verbosity:0 idetools --trackDirty:d:\appdata\local\temp\tmp2khv83.nim,D:\Documents\Code\Nim\Markdown\test.nim,3,4 --suggest

When running this command manually on Windows 7 with the following Nim configuration:

    C:\Users\cryzed>nim -v
    Nim Compiler Version 0.12.1 (2015-12-02) [Windows: i386]
    Copyright (c) 2006-2015 by Andreas Rumpf

    git hash: 93ea2e0752386107a2ffe7ee5a3e34952c6912c8
    active boot switches: -d:release

I get the following error:

    Error: cannot open 'c:\users\cryzed\.nim'

After creating this file (it has to be a file) it *seems* to work. I also added code to print the returned lines, but I only ever get a single empty line -- which matches with what I get when entering this command manually, so I'm not sure what's going wrong at this point. For the record, the source file looks like this:

```nim
proc main() =
  var a: string = "Hello World"
  a.|

main()
```

The position of the cursor is marked as '|'. I expected to get suggestions for procedures that work on string types contained in the system module.

**Comment by Varriount** [comment]
These glitches are present because the restructure-heirarchy branch is in a mixed state as far as idetool implementation goes. If you look, you'll see that although ``/nimlime_core/utils/idetools.nim`` has been rewritten, none of the idetool-related commands have been updated to use the new functions. This is why that old settings key is being used.
Additionally, the current version of nimsuggest isn't going to work with the implementation at all. The current command line interface and protocol are quite horrid, and since my pull request [to remedy that](https://github.com/nim-lang/nimsuggest/pull/18) is likely not going to be accepted, a custom implementation is going to be bundled with the plugin for the time being.

**Comment by cryzed** [comment]
That's unfortunate to hear, but I'm glad you have a solution in mind. I'm a bit confused to be honest about the idetools command for the nim executable - does it simply transparently call the nimsuggest executable found on the path, or is it simply a baked in version of nimsuggest. The whole tooling seems and is confusing to me.

So from what I understood you'll ship a custom nimsuggest executable and this will be used instead of the nim idetools command-line switch?

**Comment by Varriount** [comment]
So, the first implementation came in the form of the `nim idetools` command. The functionality was later split off into a standalone implementation, 'nimsuggest'.
The plan is to bundle the source-code of a modified form of nimsuggest with NimLime, and automatically compile it (using the system's Nim compiler) on installation of the plugin.

**Comment by cryzed** [comment]
Do you have any concrete plans for when you'll get around to doing all this? I'd be really interested in seeing this working well, although I've found a solution that works more or less for me, I think in the long run I'd still feel more at home with Sublime Text.

**Comment by Varriount** [comment]
I'm entering finals week right now. I have a basic implementation ready, but it's not as all stable. I guess I could push it? Auto suggest is going to take work.

**Comment by cryzed** [comment]
That would be great, and good luck!
