### ISSUE TITLE
Get rid of type section auto complete

### ISSUE THREAD

**Issue by dom96** [Varriount/NimLime#57]
Typing in ``type`` followed by Enter shouldn't end up with:

```nim
type name = object
```

That's not idiomatic Nim. Type sections are designed to allow multiple type definitions. Also, there may be times when I want a 'ref object' or an 'enum' or something completely different. This is simply a nuisance.

**Comment by onionhammer** [comment]
1) You can use tab to navigate the pointer to different section of the snippeted code, allowing to inject decorations like 'ref'
2) You don't have to use the snippet, just type space before you type enter.
3) type blocks are ugly.

**Comment by dom96** [comment]
1) Fair enough
2) Pressing Enter right after typing ``type`` is in my muscle memory.
3) I disagree. Also, there are times when they are necessary.

Is there at least a way to disable these?

**Comment by onionhammer** [comment]
@Varriount if we don't already have a setting for this, it might be nice to have - but I'm not sure how to disable snippets via python code.

**Comment by Varriount** [comment]
There might be a way via filesystem manipulation. I don't know of any way using the api though, not unless we want to do something similar to comment continuation.

**Comment by dom96** [comment]
That reminds me... comment continuation is done incorrectly when the previous comment is indented.

```
proc foo() =
  ## hello<press_enter>
```

->

```
proc foo() =
  ## hello
## 
```

**Comment by Varriount** [comment]
That's odd... The code actually doesn't indent by itself, it relies on the built-in automatic indentation mechanism.

**Comment by Varriount** [comment]
Turning to the issue at hand, ST2 and 3 currently lack a way for a user to disable individual snippets easily. Short of removing the entire package, the only way to remove a snippet is to delete it's corresponding file (In this case, all snippets are located in `./Support/Snippets/`). The problem with this is that the snippet will be re-installed the next time the package is updated.

**Comment by dom96** [comment]
I still vote for just removing this snippet entirely. Even if it's useful to the developers who like the single-line ``type`` syntax, it doesn't even save that much typing.

**Comment by onionhammer** [comment]
It's the difference between 5 keystrokes and 15 for an ident of 1 character..

**Comment by onionhammer** [comment]
You can also type

`type {ctrl+enter}` to go to the next line without using a snippet.

**Comment by dom96** [comment]
Thanks :)
