### ISSUE TITLE
nimline cant load nim or nimble using Linux PATH (colon, not semicolon PATH sep)

### ISSUE THREAD

**Issue by ThePythonicCow** [Varriount/NimLime#59]
The nimlime_core/utils/misc.py:def split_semicolons(string) routine does not work on Linux
[
As described here: http://stackoverflow.com/questions/4528438/classpath-does-not-work-under-linux, the PATH component separator on Linux is colon ':', not semicolon ';'

So nimlime is not loading for me on Linux, because it cannot find nim or nimble.

It ends up looking for a file that has a path that is my entire (100 char, multiple dirs) $PATH long.

The Python char os.pathsep should work reliably, on any OS (colon or semicolon, as the case be)

**Comment by Varriount** [comment]
Doesn't pathsep == '/' though?

**Comment by ThePythonicCow** [comment]
You wrote:
>> Doesn't pathsep == '/' though?

No, as you've already figured out, Python os.pathsep is colon ':' on
Linux (and I presume semi-colon ';' on Windows.)

The Python os.sep char is '/' on Linux

-- 
                Paul Jackson
                pj@usa.net

**Comment by ThePythonicCow** [comment]
I don't know the significance of the caret '^' in PATH's on Windows, but
on Linux, only the os.pathsep colon ':' can separate the directories
listed in $PATH, and your misc.py:split_pathlist() routine could be
deleted, and the call to it replaced with the one-liner:

pl = os.environ.get('PATH', '').split(':')

-- 
                Paul Jackson
                pj@usa.net

**Comment by ThePythonicCow** [comment]
Correction - use os.pathsep for colon:

pl = os.environ.get('PATH', '').split(os.pathsep)

-- 
                Paul Jackson
                pj@usa.net

**Comment by Varriount** [comment]
It should be fixed now. The caret is used on Windows as the escape character (something which Linux lacks, which is surprising).

**Comment by ThePythonicCow** [comment]
>> The caret is used on Windows as the escape character (something which
>> Linux lacks, which is surprising).

Not surprising at all in my view.

That little bit of generality, allowing the path separator character to
be embedded in any of the directory paths listed in the executable
search $PATH, by using the caret escape character, forced you to replace
a trivial one-liner that you might have coded perfectly the first time,
with a 25 line routine that has cost you a fair bit of time.

I have been closely involved with Unix and Linux file systems and their
layout and such for almost 40 years.  Never have I felt the least
motivation to embed a colon ':' in one of the directory pathnames that I
wanted to include on $PATH, and even if I had ever wanted to do that, I
could have easily chosen some way to avoid doing that.

Gratuitous generality, where it serves no particularly useful
purpose, but rather mostly just introduces complications, is usually
to be avoided.

Or at least that's how I see it in this case :).

-- 
                Paul Jackson
                pj@usa.net

**Comment by Varriount** [comment]
Well, I could have gone the simple route and used str.split, hoping that no one uses semicolons in their paths, but I'm paranoid about things like this.
