### ISSUE TITLE
nimlime_core/configuration.py gen_exe_check ".exe" check should be windows only

### ISSUE THREAD

**Issue by ThePythonicCow** [Varriount/NimLime#60]
I got this from scanning strace output and code reading, not from actually hitting on it in the wild, so it's rather low priority.

The nimlime_core/configuration.py gen_exe_check ".exe" check should be Windows only.  On Windows,  executable"foo" might mean "foo.exe" (or so I presume ... I'm only an amateur in Windows), but on Linux, "foo" means "foo", not any variant with suffix added.

(ignorant side query ... if ".exe" can be added in Windows, why not also ".com"?)

**Comment by Varriount** [comment]
Well, 'com' could be added, but as there's virtually no difference to a regular 'exe' (other than hinting that the executable is of an old MS-DOS format) and that I have yet to see anything output that format by default, I'd be wondering why it needs to be implicitly searched for.

Keep in mind that setting 'nim.com' for an executable value should still work. The code first searches for the raw executable value in all directories located in the PATH environment variable, then appends an '.exe' and does the same thing. Next it treats the raw value as a path (again, appending a '.exe' if the initial search fails.

I guess that I could read the PATHEXT variable, but that seems overkill.

Anyway, I should be able to come up with a fix for this soon.

**Comment by ThePythonicCow** [comment]
Feel free to fix or not ... as suits your whims :).

The only two risks I can see are both remote:
1) Someone on a Linux system would be surprised if the attempt to exec nim or nimsuggest failed because they happened to also have a nim.exe or nimsuggest.exe on their $PATH.  The odds are very high that that will never happen in the entire history of nimlime.
2) Someone familiar with the old .com suffix on Windows executables might expect nim.com or nimsuggest.com to be successfully executed, if found first on the PATH.  I'll leave that up to your greater experience as to how likely that is.  The last time I did any serious Windows work was back when it was called DOS 3.1 ... so my experience is long forgotten and no longer relevant.

Do whatever you think is the best use of your time ... which may well be to close this as unfixed.
