### ISSUE TITLE
'Nimsuggest doesn't appear to have been setup correctly'

### ISSUE THREAD

**Issue by EarthCitizen** [Varriount/NimLime#61]
Getting this when trying to run the nimsuggest setup:

> error: Nimsuggest doesn't appear to have been setup correctly.
> Please look at the output of the debug console (ctrl+`) for more information.
> error: Nimsuggest doesn't appear to have been setup correctly.
> Please look at the output of the debug console (ctrl+`) for more information.
> Traceback (most recent call last):
>   File "/Users/someuser/Library/Application Support/Sublime Text 3/Installed Packages/NimLime.sublime-package/nimlime_core/commands/idecommands.py", line 103, in run
>     shutil.copy(nimsuggest_src_exe, exe_path)
>   File "./shutil.py", line 227, in copy
>   File "./shutil.py", line 109, in copyfile
> FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/1v/99sqkxrn38jcmx0qw4wj5znm00999n/T/tmp01zn77/nimsuggest/nimsuggest'

**Comment by Varriount** [comment]
Hm, odd. I'm assuming you're on OSX? If so, could you possibly use [dtruss](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dtruss.1m.html) to see what folders are being created? Either that, or I can look into posting a modified package with some print statements.

**Comment by partisanyc** [comment]
My issue is the same as the above, but on Ubuntu. In my case, the directory exists and nim sources for nimsuggest are there, but the compiled nimsuggest executable is not there. 

Also, should I close my issue as a duplicate?

**Comment by Varriount** [comment]
@partisanyc I'll do it.

@partisanyc @EarthCitizen Could you two please update your NimLime installs (I just pushed a new minor release) and check if the problem still happens? If the problem persists, open up the user local settings for nimlime and add the setting key `'debug_mode': true`, and re-run the command, then paste the output here.

**Comment by partisanyc** [comment]
Here is the output:

> exe_dir: /home/leif
temp_dir: /tmp/tmp0k4imt
nimlime_dir: /home/leif/.config/sublime-text-3/Installed Packages/NimLime.sublime-package
nimsuggest_tmp_exe: /tmp/tmp0k4imt/nimsuggest/nimsuggest
Extracting nimsuggest tarball to temp_dir
Exception in thread Thread-6:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "./threading.py", line 858, in run
  File "/home/leif/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/utils/misc.py", line 215, in _run_process_worker
    **kwargs
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1370, in _execute_child
  File "./os.py", line 811, in fsencode
TypeError: expect bytes or str, not NoneType

**Comment by partisanyc** [comment]
I am somewhat new to this so forgive me. 

So suddenly, I am back to getting the 'Nim executable not found' error. I am running subl from the command line just as I was before, but it doesn't seem to see the executable now even though it is on the PATH. 

Right now, when I run Nim: Check Current File, it hangs on "Running Num Check...", but I suspect this is due to the PATH issue. I'll try to fix it tonight and let you know what I fund.

**Comment by partisanyc** [comment]
Ok, I guess I have to set the absolute path to nim and nimble and they were wiped out when I removed and reinstalled the NimLime package. For some reason, it doesn't seem to be picking them up from $PATH. 

Anyway, with that fixed, I was able to get further with Setup Nimsuggest.

Here are the contents of console.

> Running for real
exe_dir: /home/leif
temp_dir: /tmp/tmpe0_rmg
nimlime_dir: /home/leif/.config/sublime-text-3/Installed Packages/NimLime.sublime-package
nimsuggest_tmp_exe: /tmp/tmpe0_rmg/nimsuggest/nimsuggest
Extracting nimsuggest tarball to temp_dir
  File "<string>", line 13, in error_handler
error: The NimLime plugin has encountered an error. Please go to  https://github.com/Varriount/NimLime and create a new issue containing the contents of the logging file at:
'/tmp/NimLime-Log.txt'.
Though this error message is only displayed once per session of Sublime Text, further errors will be logged to the logging file and indicated in the status bar.
To completely suppress this error message in the future, change the 'error_handler.enabled' setting in NimLime's settings file to 'False'.
Traceback (most recent call last):
  File "<string>", line 11, in error_handler
  File "/home/leif/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/commands/idecommands.py", line 104, in run
AttributeError: 'module' object has no attribute 'nim_executable'


Here are the contents of NimLime-Log.txt.

> 2016-02-20: 22:19:19
[Stack frames]
[Thread 140361480197888]
  File "/opt/sublime_text/sublime_plugin.py", line 346, in on_deactivated_async
    callback.on_deactivated_async(v)
  File "save_on_focus_lost in /opt/sublime_text/Packages/Default.sublime-package", line 8, in on_deactivated_async
  File "/opt/sublime_text/sublime.py", line 629, in file_name
    name = sublime_api.view_file_name(self.view_id)
[Thread 140361498011520]
  File "<string>", line 14, in error_handler
  File "/home/leif/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/utils/error_handler.py", line 134, in _handle_error
    traceback.print_stack(stack_frame, file=logfile)
Main Traceback (most recent call last):
  File "<string>", line 11, in error_handler
  File "/home/leif/.config/sublime-text-3/Installed Packages/NimLime.sublime-package/nimlime_core/commands/idecommands.py", line 104, in run
    [configuration.nim_executable, 'c', '-d:release', 'nimsuggest.nim'],
AttributeError: 'module' object has no attribute 'nim_executable'

**Comment by Varriount** [comment]
Are you using the latest version? (As in, you added the repository manually to Package Control, and then installed NimLime)

If so, it might be easier if you reverted to the stable version - I often make changes that aren't fully tested on the main branch (although, I guess I could just use a separate branch)

**Comment by partisanyc** [comment]
Yes. The version I have now is:

Super Nim Plugin for Sublime Text 2/3
v2016.02.20.23.20.32; github.com/Varriount/NimLime

Not to worry, I am able to work with things the way they are, but I am open to help test/debug if needed. Thanks for the great plugin!

**Comment by Varriount** [comment]
@partisanyc What error (if any) do you get now, with the latest repo?

**Comment by partisanyc** [comment]
Sorry for the delay. Here is my current NimLime.sublime-settings file:

> {
  "debug_mode": "true",
    "nim.executable": "/home/leif/Documents/nim/Nim/bin/nim",
    "nimble.executable": "/home/leif/Documents/nim/nimble/nimble",
    "nimsuggest.executable": "nimsuggest",
}

The following is the output when attempting to Setup Nimuggest through command palette. 

> exe_dir: /home/leif
temp_dir: /tmp/tmpsu18qo
nimlime_dir: /home/leif/.config/sublime-text-3/Installed Packages/NimLime.sublime-package
exe_output_file: /home/leif/nimsuggest
Extracting nimsuggest tarball to temp_dir
Compiling with Nim exe: /home/leif/Documents/nim/nimble/nimble
error: Nimsuggest doesn't appear to have been setup correctly.
Please look at the output of the debug console (ctrl+`) for more information.
Compilation unsuccessful.
FAILURE: Specified directory does not contain a .nimble file.
Unable to open /home/leif/.config/sublime-text-3/Packages/User/NimLime/NimLime.sublime-settings

**Comment by Varriount** [comment]
Ok, this should be fixed - It turned out to be a problem with the Nimsuggest source & file system case-sensitivity. I've tested it on a local Ubuntu VM, and it works.
