### ISSUE TITLE
nim and nimsuggest not found on startup

### ISSUE THREAD

**Issue by c4stan** [Varriount/NimLime#63]
On Windows, whenever i open Sublime Text i get the error message that nim and nimsuggest aren't in my PATH, but they are. I can open a terminal, type either 'nim' or 'nimsuggest' and they work. In Sublime, i can also build with ctrl+b and it works. The config file is setup correctly (i haven't changed anything and the names seems correct, e.g. 'nim')

**Comment by Varriount** [comment]
This should be fixed in the latest minor release (just created the update). Is it fixed?

**Comment by c4stan** [comment]
Seems fixed. Thanks!

**Comment by Varriount** [comment]
Note that this changes how executables are checked for. Instead of checking ahead of time, the code that invokes subprocesses catches errors and reports them in the status bar. If NimLime still can't find your executable, it means the system can't find it.
