### ISSUE TITLE
Support for #[ ]# comments?

### ISSUE THREAD

**Issue by oderwat** [Varriount/NimLime#64]
Am I right that support for #[ ]# comments is missing?

**Comment by Varriount** [comment]
Yes. For basic support, the language files need updating. For advanced support, the doccomment feature (located in /nimlime_core/commands/doccontinue.py ) needs to be updated to generate the closing tag automatically.

**Comment by Varriount** [comment]
Ok, semi-support has been added in the master branch, however the settings file is going to need to be renamed (the new snippet based approach only loads settings from the view).

**Comment by oderwat** [comment]
I asked because I was searching an updated nim language TM file to update the textmate bundle which I then import into PHPStorm ;-). So I thought your implementation has it already. I found an update which is part of the VSCode Nim extension and created a PR for the textmate bundle. Also available on GitHub. I guess I am going to check where (and if) your and the other implementations differ. Thank you for adding it to NimLime. Sadly I could not get Sublime Text to work for me in the past.

**Comment by Varriount** [comment]
Oh? Was your trouble with NimLime specifically, our just Sublime Text in general?

**Comment by oderwat** [comment]
At that time I was using "CodeRunner" (for Mac) already and I could not get SublimeText to just "compile & run" the open file easily. I also hat problems with Nimsuggest not working. SublimeText also always gives me headaches about simple operations like global text replace. I guess it simply is not for me :) .. But all of this is "long" ago and may be corrected now.

**Comment by Varriount** [comment]
@oderwat Ok, this has been implemented. Typing `#[` will automatically add ` ]#` after the cursor.
