### ISSUE TITLE
NimLime creates a whole menu just for itself

### ISSUE THREAD

**Issue by mcclure** [Varriount/NimLime#73]
It is present even when I am not writing Nim, and it doesn't contain anything but a link to this Github page. Is there a way to turn it off?

**Comment by onionhammer** [comment]
Yeah, this should not be there. I think we should get rid of it.

**Comment by Varriount** [comment]
I had some thoughts that other things could be added to it, but of it bothers you that much, I guess the entry could be moved to preferences.
I'd just prefer that a link to the issues page was displayed *somewhere*, to try and encourage users to actually report problems.

**Comment by mcclure** [comment]
It makes sense! Just, a top level menu visible for all types of files seems like overkill.

**Comment by Varriount** [comment]
@mcclure I've placed the menu in the preferences section for now. (although I wonder if I could create a top-level menu conditionally).
