### ISSUE TITLE
CMD + Click selection addition removed with this package

### ISSUE THREAD

**Issue by adambullmer** [Varriount/NimLime#77]
After installing this package, my Selection Addition functionality no longer works. In particular the `CMD` + `Left Mouse Click`. I looked through your default settings and key bindings and didn't see an option that looked like changing it would have any effect on this behavior.

See: http://www.sublimetext.com/docs/selection in the "Using the Mouse" section.

Mac OS El Capitan `10.11.6`
Sublime Text `3126`

**Comment by Antrikshy** [comment]
I'm pretty sure [this](https://github.com/Varriount/NimLime/blob/master/Default%20(OSX).sublime-mousemap) is what's causing it.

**Comment by Varriount** [comment]
Is this for all OS's, or just OSX?

**Comment by adambullmer** [comment]
I only tested on OSX, I can try and reproduce on other systems later tonight though

**Comment by Varriount** [comment]
Fixed with newest release. I've purged the mousemaps for now - I'll need to think on a better way to activate IDE features without breaking selections.
