### ISSUE TITLE
Nim syntax highlighting apostrophe type suffix 

### ISSUE THREAD

**Issue by lbmn** [Varriount/NimLime#82]
I hope I've [understood](https://github.com/github/linguist/blob/master/grammars.yml) [correctly](https://github.com/github/linguist/blob/master/vendor/README.md) that this is used for GitHub's syntax highlighting of Nim source code...

If so, it seems that it doesn't support the apostrophe [type suffix](https://nim-lang.org/docs/manual.html#lexical-analysis-numerical-constants) correctly with number literals containing letters (ex. hex and binary):

```nim

let hex = 0xDEADBEEF'u32
let bin = 0B0_10001110100_0000101001000111101011101111111011000101001101001001'f64
```

**Comment by Varriount** [comment]
Huh, I never knew that. Does that mean NimLime controls all of Github highlighting for Nim? 😈

Anyway, I'll see what I can do to fix this.

**Comment by Varriount** [comment]
@lbmn Well, the current syntax file highlights correctly in Sublime Text. Do you know if I need to file a ticket with the Linguist project to update the syntax? Or, is there a difference in the syntax supported by Sublime Text?

**Comment by dom96** [comment]
Yeah, that's what you need to do it looks like. You might be able to create a PR as well, this project is in there as a submodule: https://github.com/github/linguist/tree/master/vendor/grammars

**Comment by lbmn** [comment]
Continued at github/linguist#3631  :smiley: 

For future reference, here's what the bug looked like before it was fixed - https://archive.is/HG9fj

**Comment by Varriount** [comment]
This appears to be fixed now.
