### ISSUE TITLE
documentation comments don't highlight correctly: ##[ ... ]##

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#95]
eg:
```nim
##[
Universal conversion template.
]##
```
![image](https://user-images.githubusercontent.com/2194784/38271753-265f76c4-373c-11e8-8dc7-70fe4302012e.png)

**Comment by timotheecour** [comment]
https://nim-lang.org/docs/manual.html
Multiline documentation comments also exist and support nesting too:

proc foo =
  ##[Long documentation comment
  here.
  ]##

**Comment by Varriount** [comment]
Fixed (probably via a previous syntax change)

**Comment by timotheecour** [comment]
indeed
