### ISSUE TITLE
syntax highlight confused by asm """ """ and shows remainder as string

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#96]
https://github.com/nim-lang/Nim/blob/devel/lib/system.nim at a6f248f3d09f18daab67e25468760f722bb24201

![image](https://user-images.githubusercontent.com/2194784/38393490-cd8aaaf0-38df-11e8-956a-cd06a9769dcf.png)

**Comment by Varriount** [comment]
No longer an issue.

**Comment by timotheecour** [comment]
@Varriount the problem seems to be this line in `$nim_D/NimLime/Syntaxes/Nim.YAML-tmLanguage`:

```
- {include: source.asm}
```

if i comment it out, it works
perhaps `source.asm` needs to be somewhere for it to work? maybe another package you've installed for getting asm syntax and that should be a dependency?
anyhow, the workaround is to just comment it and rebuild `$nim_D/NimLime/Syntaxes/Nim.tmLanguage` using packagedev
