### ISSUE TITLE
"error: plugin_host has exited unexpectedly"

### ISSUE THREAD

**Issue by timotheecour** [Varriount/NimLime#99]
I'm getting a lot of these "error: plugin_host has exited unexpectedly" when editing nim files ; probably nimsuggest failing and the plugin not properly handling errors

full error:
"error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted"

**Comment by Varriount** [comment]
I've been trying to diagnose this - unfortunately it seems to have appeared with one of the more recent builds of Sublime Text.

**Comment by timotheecour** [comment]
do you have a reproducible test?

**Comment by timotheecour** [comment]
/cc @Varriount looks like I found a reproducible test case. It **always** crashes with "error: plugin_host has exited unexpectedly" when I open this file and press command+S to save it.

Please let me know whether you can reproduce it on your end.

```nim
#[
# plugin_host bug: https://github.com/Varriount/NimLime/issues/99
open this in sublime text
when use saves this file (eg on OSX: via command + S), the plugin_host will die
seems like a minimal-ish test case: variations of this file won't trigger that bug (eg removing =0, commenting a line, removing {.strdefine.} etc)
]#

const testCase {.strdefine.}: string=0
when false: discard
elif testCase == "test1":
```

**Comment by alehander42** [comment]
@timotheecour thank you, a lifesaver

**Comment by timotheecour** [comment]
closing since https://github.com/nim-lang/nimsuggest/issues/83 seems fixed now

**Comment by timotheecour** [comment]
re-opening because of a new case that causes the crash: https://github.com/nim-lang/Nim/issues/9610

**Comment by timotheecour** [comment]
ok that bug was fixed; but to prevent future similar bugs, how about following:
* restart the process that runs `nim fix` if it crashes (and write to a log so we don't ignore)

**Comment by timotheecour** [comment]
/cc @Varriount I found a great workaround:
install latest sublime dev channel https://www.sublimetext.com/3dev 
this build: `BUILD 3179` introduced this feature:
> Mac: Fixed a plugin_host crash when running a process that itself crashes

and I verified it fixes this issue on OSX
